In [4]:
myVar = 'Danolina'


In [7]:
print(myVar)

Danolina


In [8]:
myVar

'Danolina'

In [9]:
"Her name is {} and my name is {}"

'Her name is {} and my name is {}'

In [10]:
myName = 'Daniel'
herName = 'Carolina'

'My name is {} and her name is {}'.format(myName,herName)

'My name is Daniel and her name is Carolina'

In [13]:
my_list = [1,2,3]

In [14]:
import numpy as np

In [15]:
np.array(my_list)

array([1, 2, 3])

In [16]:
arr

NameError: name 'arr' is not defined

In [17]:
arr = np.array(my_list)

In [18]:
arr

array([1, 2, 3])

In [19]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [20]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arrange(0,10)

AttributeError: module 'numpy' has no attribute 'arrange'